v10
timgit/pg-boss pull request #425
Opened 2023-09-10 22:01 UTC by timgit

2023-09-11 09:43 UTC, StarpTech requested changes
Great work! Only a few points.

2023-09-11 09:43 UTC, StarpTech commented on src/index.js
> +    let { destroy = false, graceful = true, timeout = 30000, wait = false } = options
Can we make `wait=true` the default behavior in v10? I think nobody wants to forcefully exit jobs by default.

2023-09-11 09:43 UTC, StarpTech commented on src/db.js
> +  async lock ({ timeout = 30, key } = {}) {
I'm a friend of giving variables units. Maybe timeoutSeconds?

2023-09-11 09:43 UTC, StarpTech commented on src/db.js
> +      // if (this.config.debug === true) {
Can we delete it when not used?

2023-09-11 09:43 UTC, StarpTech commented on types.d.ts
> +    state: 'created' | 'retry' | 'active' | 'completed' | 'cancelled' | 'failed',
Could you add "stopping" here? Then we can complete https://github.com/timgit/pg-boss/issues/422 as well.

2023-09-13 09:14 UTC, StarpTech commented on releasenotesv10.md
> +* MAJOR: **Job retries are now opt-out instead of opt-in.** The default `retryLimit` is now 2 retries. This will cause an issue for any job handlers that aren't idempotent. Consider setting `retryLim
I think this is not a good default. Configure retries when necessary seems to be a better option.

2023-09-15 08:39 UTC, StarpTech commented
@timgit are you open to feedback? You resolved all my comments without an answer.

2024-03-18 13:29 UTC, KristjanTammekivi commented
Hi, is there any progress here? I would like to have the graceful shutdown to be implemented (#421)

2024-03-20 23:03 UTC, timgit commented
Apologies for the long turn around time on this release. There's a few problems I'm still looking at.

2024-04-29 09:38 UTC, sneljo1 commented
Which items are still open for this?

2024-08-17 19:01 UTC, merged

2024-08-29 07:39 UTC, janmeier commented
@timgit Can you put a couple of words on the motivation behind this major version? Which issues does this solve?

I'm saying this with the utmost understanding of what it means to release something as open source - This is your project, and I don't expect you to justify every decision. Still, I'm just curious about the reasoning, and I want to hear about any improvements that should cause us to consider upgrading :)

2024-08-29 19:54 UTC, timgit commented
The primary motivation is stability and scalability. In my and others' experience, once a single queue exceeded 1-2mil created jobs in a backlog state, postgres was unable to quickly locate the next record for locking via SKIP LOCKED.  This is mentioned as a limitation in the linked article in the readme.  This produced high memory and CPU utilization issues on the server, which would then impact all other databases. The problem with pg-boss v9's design is that once any queue reaches this failure state, all queues, including internal maintenance queues, were affected since all jobs shared a single table. The design goal was to mitigate a problematic queue by isolating its storage into a dedicated table via partitioning. This doesn't necessarily remove this limitation of SKIP LOCKED, but it should in theory be less of a catastrophic failure if and when it occurs in the future.

Over the years, there were several issues opened around queue concurrency, which added several functions and configuration which made the API more complicated and difficult to understand (`sendSingleton()` and others). There were several ideas that I wanted to prototype, which resulted in queue policies, the biggest feature enhancement worth upgrading for. 

After a couple of failed attempts at building a reasonable migration plan into the new table structure, I decided it was best to release v10 without a schema migration.  This wasn't my first choice, but I think it still was the cleanest way to make it predictable what to expect between these versions.